# name: Node Tests Coverage

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#     - uses: actions/checkout@v1
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: npm install, build, and run coverage
#       run: |
#         npm ci
#         npm run build --if-present
#         npm run coverage
#       env:
#         CI: true
#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v1.0.3
#       with:
#         token: ${{secrets.CODECOV_TOKEN}}

